-- Code Generated by Sidekick is for learning and experimentation purposes only.

-- FILE: sql/migrations/V001__create_enrollment_table.sql
-- PURPOSE: Creates the staging schema and enrollment table
-- NOTE: Uses parameterized procedures downstream — no dynamic SQL

-- Create staging schema if it doesn't exist
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'staging')
BEGIN
    EXEC('CREATE SCHEMA staging');
END
GO

-- Create the enrollment staging table
CREATE TABLE staging.Enrollment (
    EnrollmentID        INT IDENTITY(1,1) PRIMARY KEY,
    ChildID             NVARCHAR(50)    NOT NULL,
    ChildFirstName      NVARCHAR(100)   NOT NULL,
    ChildLastName       NVARCHAR(100)   NOT NULL,
    DateOfBirth         DATE            NOT NULL,
    GuardianID          NVARCHAR(50)    NOT NULL,
    ProviderID          NVARCHAR(50)    NOT NULL,
    EnrollmentDate      DATE            NOT NULL,
    EligibilityStatus   NVARCHAR(20)    NOT NULL DEFAULT 'Pending',
    SubsidyAmount       DECIMAL(10,2)   NULL,
    SourceFileName      NVARCHAR(255)   NULL,
    LoadTimestamp       DATETIME2       NOT NULL DEFAULT SYSUTCDATETIME(),

    -- Constraints for data integrity
    CONSTRAINT CK_Enrollment_Eligibility
        CHECK (EligibilityStatus IN ('Pending', 'Approved', 'Denied', 'Expired')),
    CONSTRAINT CK_Enrollment_SubsidyPositive
        CHECK (SubsidyAmount IS NULL OR SubsidyAmount >= 0)
);
GO

-- Index for common query patterns
CREATE NONCLUSTERED INDEX IX_
